Add changes to wait for Elasticsearch registry path to be available when using Elasticsearch with security enabled
NASA-PDS/registry-harvest-service pull request #19
Opened 2022-03-02 23:07 UTC by ramesh-maddegoda

## 🗒️ Summary
Add changes to wait for Elasticsearch registry path to be available when using Elasticsearch with security enabled

## ♻️ Related Issues
Refer to task NASA-PDS/pds-registry-app#250

2022-03-24 18:33 UTC, tloubrieu-jpl requested changes
Hi @ramesh-maddegoda,

I am having a lot of the following errors when I run the command:
`docker compose --profile=int-registry-service-loader up` (in the registry repository)

`docker-elasticsearch-1                       | [2022-03-24T18:30:46,690][ERROR][o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport] [8d5f78b3def7] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
docker-elasticsearch-1                       | javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
docker-elasticsearch-1                       | 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:133) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
docker-elasticsearch-1                       | 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637) ~[?:?]
docker-elasticsearch-1                       | 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282) ~[netty-handler-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1387) ~[netty-handler-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282) ~[netty-handler-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329) ~[netty-handler-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[netty-codec-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at java.lang.Thread.run(Thread.java:832) [?:?]
docker-elasticsearch-1                       | Caused by: javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1895) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160) ~[?:?]
docker-elasticsearch-1                       | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[?:?]
docker-elasticsearch-1                       | 	... 27 more
docker-elasticsearch-1                       | [2022-03-24T18:30:46,692][WARN ][o.o.h.AbstractHttpServerTransport] [8d5f78b3def7] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/172.19.0.6:9200, remoteAddress=/172.19.0.8:57648}
docker-elasticsearch-1                       | io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
docker-elasticsearch-1                       | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478) ~[netty-codec-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
docker-elasticsearch-1                       | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHa [...]

2022-03-24 19:03 UTC, ramesh-maddegoda commented
> Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment

@tloubrieu-jpl , this was the known issue (https://github.com/tkohegyi/mitmJavaProxy/issues/12) that I also faced. However it  did not appear after all the changes made in the docker-compose of the registry. I will check this.

2022-03-31 17:04 UTC, tloubrieu-jpl approved these changes

2022-03-31 17:05 UTC, tloubrieu-jpl commented
Good I was able to make it work, in my previous test I might have use an outdate docker image. Thanks @ramesh-maddegoda

2022-03-31 17:05 UTC, merged